# Generated by Django 2.2 on 2019-04-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechReviewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techtype',
            options={'verbose_name_plural': 'producttypes'},
        ),
        migrations.AlterModelTable(
            name='techtype',
            table='productype',
        ),
    ]
